version: '3'

services:
  server:
    build: ./backends
    expose:
      - ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    volumes:
      - ./backends:/srv/app/eficode19-backend
    command: npm run watch

  client:
    build: ./frontend
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports: 
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
      - ${REACT_RELOAD_PORT}:${REACT_RELOAD_PORT}
    volumes:
      - ./frontend/src:/srv/app/eficode19-frontend/src
      - ./frontend/public:/srv/app/eficode19-frontend/public
    links:
      - server
    command: npm start